---
# Entrypoint for Zuul
- project:
    check:
      jobs:
        - pre-commit
        - packit-service-tests
    #        - packit-service-tests-openshift
    gate:
      jobs:
        - pre-commit

- job:
    name: packit-service-tests
    parent: base
    description: Run tests of packit-service
    run: files-avant/zuul-tests.yaml

- job:
    name: packit-service-tests-openshift
    parent: oc-cluster-up
    description: Run tests with service being deployed including database (e.g. for database or requre tests)
    # this will clone the deployment repo to a predictable path
    required-projects:
      - github.com/packit/deployment
    extra-vars:
      with_testing: true
      deployment: dev
    pre-run:
      - files-avant/packit-service-image.yaml
      - files-avant/deployment.yaml
      # having the check as separate job would be nicer, but waste of resources
      - files-avant/deployment-check.yaml
    run: files-avant/zuul-tests-requre.yaml
