# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: This is a recipe for a container image where packit-service tests will run
  hosts: all
  tasks:
    - name: Install test RPM dependencies
      ansible.builtin.dnf:
        name:
          - tar
          - rsync
        state: present
    - name: Install pip deps
      ansible.builtin.pip:
        name:
          - requre
          - flexmock
          - pytest
          - pytest-cov
          - pytest-flask
          - deepdiff < 8.0.0 # version 8.0.0 requires numpy, avoid it
