---
kind: Pod
apiVersion: v1
metadata:
  name: get-requre-data
  labels:
    app: get-requre-data
spec:
  volumes:
    - name: test-data-pv
      persistentVolumeClaim: { claimName: test-data-pvc }
  restartPolicy: Never
  containers:
    - name: packit-tests
      image: quay.io/packit/packit-service-tests:stg
      # If tag is latest, defaults to Always.
      # imagePullPolicy: Never # IfNotPresent
      workingDir: /src
      volumeMounts:
        - name: test-data-pv
          mountPath: /tmp/test_data
      command: ["bash", "-c", "sleep 10000"]
