# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Install dependencies for packit-service worker
  hosts: all
  vars:
    source_branch: "{{ lookup('env', 'SOURCE_BRANCH') }}"
    deployment: "{{ lookup('env', 'DEPLOYMENT', default='stg') }}"
  tasks:
    - import_tasks: tasks/process-source-branch.yaml
    - name: Install all RPM/python packages needed to run packit-service worker
      ansible.builtin.dnf:
        name:
          - nss_wrapper # openshift anyuid passwd madness
          - python3-pip
          - python3-requests
          - python3-prometheus_client
          - python3-sqlalchemy
          - python3-psycopg2
          - python3-redis
          - python3-lazy-object-proxy
          - python3-sentry-sdk
          - python3-syslog-rfc5424-formatter # logging to Splunk
          - dnf-utils
          - make
          # for pip-installing sandcastle from git repo
          - git-core
          # oc rsync /tmp/sandcastle -> sandcastle pod
          - rsync
          - postgresql # pg_dump
          - python3-boto3 # AWS (S3)
          - python3-fasjson-client
          - python3-gevent # concurrency pool, see run_worker.sh
          - bodhi-client
          # sandcastle deps
          - python3-charset-normalizer
          - python3-google-auth
          - python3-oauthlib
          - python3-pyyaml
          - python3-requests-oauthlib
          - python3-websocket-client
          # for the `pkg_tool` switch to allow centpkg
          - centpkg
          - gcc
          - libffi-devel
          - python3-devel
        state: present
        install_weak_deps: False
    - name: Install pip deps
      ansible.builtin.pip:
        name:
          - git+https://github.com/packit/sandcastle.git@{{ source_branch }}
          - eventlet
          - celery
      #    - name: Install guppy3 for memory profiling in non production environments
      #      ansible.builtin.pip:
      #        name:
      #          - guppy3
      when: deployment != 'prod'
    - name: Check if all pip packages have all dependencies installed
      command: pip check

    - name: Install custom python3-ogr package from local RPM
      ansible.builtin.dnf:
        name: /src/files/python3-ogr.rpm
        state: present
        disable_gpg_check: true
    - name: Install specfile and packit from copr
      ansible.builtin.dnf:
        name:
          - python3-specfile
          - packit
        state: latest
    - name: Install OpenScanHub client from Copr
      ansible.builtin.dnf:
        name: osh-client
        state: latest
    - name: Install OKD CLI (oc) # sandcastle
      ansible.builtin.unarchive:
        src: https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
        remote_src: true
        dest: /usr/bin/
